RoutingAndAreas/Routing001/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Routing001.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ShowOutRoutes()
        {
            return View();
        }

    }
}

RoutingAndAreas/Routing001/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Routing001.Controllers
{
    public class MyController : Controller
    {
        //
        // GET: /My/

        public ActionResult About()
        {
            return View();
        }

    }
}

RoutingAndAreas/WorkingWithAreas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkingWithAreas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RoutingAndAreas/Routing001/Views/Home/ShowOutRoutes.cshtml
@{
    ViewBag.Title = "ShowOutRoutes";
}

<h2>ShowOutRoutes</h2>
<ul>
    <li>@Html.ActionLink("Go to Home/About", "About")</li>
    <li>@Html.ActionLink("Go to My/About", "About", "My")</li>
    <li>@Html.ActionLink("Go to Home/About/MyID", "About", new {id = "MyID"})</li>
    <li>@Html.ActionLink("Go to Home/About/MyID?myVar=mvValue", "About", new {id = "MyID", myVar="myValue"})</li>
    <li>@Html.ActionLink("Go to /", "Index", "Home")</li>
    <li>@Html.ActionLink("Go to /", "Index", "Home", null, new {id = "htmlId", @class="cssClass"})</li>
    <li>URL: @Url.Action("Index", "Home", new { id = "MyId" })</li>
    <li>@Html.RouteLink("Routed Link: /Home/About/MyID", new { controller = "Home", action = "About", id="MyID"})</li>
    <li>Url.RouteUrl: @Url.RouteUrl(new { controller = "Home", action = "About", id="MyID"})</li>
    <li><a href="~/old/replaceThisOldRoute">~/old/replaceThisOldRoute</a></li>
    
    


</ul>